version: "3.8"

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=matomo
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - /var/lib/mysql

  matomo:
    build: .
    env_file:
      - web-variables.env
    ports:
      - 3000:3000
    init: true

